config/routes.rb
Rails.application.routes.draw do
  devise_for :artists
  devise_for :users
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  get '/pages/dashboard', to: 'pages#dashboard'
  resources :artists, only: [:index, :show, :edit, :update] do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
    resources :tattoos, only: [:new, :create, :show] do
      resources :comments, only: [:new, :create]
    end
  end

  resources :conversations do
    resources :messages
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attachments :photos, maximum: 3
  has_many :bookings
  has_many :tattoos
  has_many :comments
  has_many :reviews
  has_many :conversations
  has_many :messages
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :artist
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tattoo
  belongs_to :user
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :artist
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :user_id, :scope => :artist_id
  validates_uniqueness_of :artist_id, :scope => :user_id

  scope :between, ->(artist_id, user_id) {
    where ('(conversations.artist_id = artist_id AND conversations.user_id = user_id) OR
    (conversations.user_id = user_id AND conversations.artist_id = artist_id)')
  }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  belongs_to :artist
  has_attachment :photo

  validates_presence_of :body, :conversation_id
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :artist
  belongs_to :user
end

app/models/tattoo.rb
class Tattoo < ApplicationRecord
  belongs_to :artist
  has_many :comments
  has_attachment :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings
  has_many :comments
  has_many :reviews
  has_many :conversations
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @artists = Artist.all
    @cities = []
    @artists.each do |artist|
      @cities << artist.city
    end
    @cities = @cities.uniq
  end

  def show
    @artist = Artist.find(params[:id])
    @booking = Booking.new
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update_attributes(artist_params)
        flash[:notice] = 'You have successfully added your photo'
        redirect_to pages_dashboard_path
    end
  end



  private

  def artist_params
      params.require(:artist).permit(:name, :city, :info, :photos)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @artist = Artist.find(params[:artist_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @artist = Artist.find(params[:artist_id])
    @booking.artist = @artist
    @booking.user = current_user

    if @booking.save
      redirect_to pages_dashboard_path
    else
      render:new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @tattoo = Tattoo.find(params[:tattoo_id])

    @comment = Comment.new
  end

  def create
    @tattoo = Tattoo.find(params[:tattoo_id])
    @comment = @tattoo.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to :back
    else
      render:new
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :tattoo_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:user_id],params[:artist_id]).present?
      @conversation = Conversation.between(params[:user_id],params[:artist_id]).first
      redirect_to conversation_messages_path(@conversation)
    else
      @conversation = Conversation.create!(conversation_params)
    end
  end

  private

  def conversation_params
    params.permit(:artist_id, :user_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if current_user
      @message.user_id = current_user.id
    end

    if current_artist
      @message.artist_id = current_artist.id
    end

    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :artist_id, :user_id, :photo, :subject)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :dashboard]

  def home
    @cities = get_cities
    @artists = Artist.all
  end

  def get_cities
    @cities = ["Choose a city"]
    @artists = Artist.all
    @artists.each do |artist|
    @cities << artist.city
    end
    @cities.uniq
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @artist = Artist.find(params[:artist_id])
    @review.artist = @artist
    @review.user = current_user
  end

  def create
    @review = Review.new(review_params)
    @artist = Artist.find(params[:artist_id])
    @review.artist = @artist
    @review.user = current_user

    if @review.save
      redirect_to artist_path(@artist)
    else
      render :new
    end

  end

  private

  def review_params
    params.require(:review).permit(:content, :artist_id, :user_id)
  end

end

app/controllers/tattoos_controller.rb
class TattoosController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @tattoo = Tattoo.find(params[:id])
    @comments = @tattoo.comments.all
    @comment = @tattoo.comments.build
  end


  def new
    @tattoo = Tattoo.new
  end

  def create
    @tattoo = Tattoo.new(tattoo_params)
    @tattoo.artist = current_artist
    if @tattoo.save
      redirect_to pages_dashboard_path
    else
      render:new
    end
  end

  private

  def tattoo_params
    params.require(:tattoo).permit(:photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_artist-tattoos.html.erb
<div class="container-artist-index">
  <div class="row artist-index-photos no-gutters">
  <% artist.tattoos.each do |tattoo| %>
    <div class="col-lg-3">
      <% if tattoo.url? %>
        <%= link_to artist_tattoo_path(tattoo.artist, tattoo) do %>
          <%= image_tag tattoo.url, class: "index-photo" %>
           <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
        <% end %>
      <% elsif tattoo.photo? %>
        <%= cl_image_tag @tattoo.photo.path, width: 250, height: 250, crop: :fill %>
      <% end %>
    </div>
  <% end %>
  </div>
</div>

app/views/artists/index.html.erb
<div class="search-artist-index text-center">
  <%= form_tag "/artists", method: "get" do |f| %>
  <%= select_tag "city", options_for_select(@cities), prompt: "Choose a city" %>
  <%= submit_tag "Discover Art", class: 'btn-primary ' %>
  <% end %>
  <% if (params[:city] != "Choose a city")  %>
    <p>Showing results for artwork in <%= params[:city] %></p>
  <% end %>
</div>

<% @artists.each do |artist| %>
<% if (params[:city] == artist.city) || (params[:city] == "Choose a city") %>
  <%= render 'artist-tattoos', artist: artist %>
<% end %>
<% end %>

app/views/artists/show.html.erb
<div class="container-profile-info">
  <div class="profile-pic">
    <%= image_tag @artist.avatar, class: "artist-avatar" %>
  </div>
  <div>
    <h3><%= @artist.name %></h3>
    <p><%= @artist.city %></p>
    <p><%= @artist.info %></p>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal">
    Book an appointment
  </button>
  <%= link_to "Reviews", "#reviews", class: "btn btn-primary" %>
  <% if Conversation.between(@artist.id, current_user.id).present? %>
    <% @conversation =  Conversation.between(@artist.id, current_user.id).ids[0] %>
    <%= link_to "Message", conversation_messages_path(@conversation), class: "btn btn-primary" %>
  <% else %>
    <%= link_to "Message", conversations_path(artist_id: @artist.id, user_id: current_user.id), :method => :post %>
  <% end %>
  </div>
</div>


<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="ModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLongTitle">Book an appointment with <%=@artist.name%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <div class="row text-center">

        <h3 class="text-center">Book your appointment</h3>
        <%= simple_form_for [@artist, @booking] do |f| %>
        <%= f.input :start_time %>
        <%= f.input :end_time %>
        <%= f.submit "Book" %>
        <% end %>
      </div>
    </div>

  </div>
</div>
</div>
</div>

<div class="container-artist-show">
<div class="row artist-show-photos no-gutters">
<% @artist.tattoos.each do |tattoo| %>
  <div class="col-lg-4">
      <%= image_tag tattoo.url, class: "show-photo" %>
  </div>
<% end %>
</div>
</div>

<div class="text-center" id="reviews">
  <%= link_to "Review", new_artist_review_path(@artist) %>
  <% if @artist.reviews.count < 1 %>
    <p>Be the first to leave a review</p>
  <% else %>
    <% @artist.reviews.each do |review| %>
    <%= review.content %>
    <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4">
   <h3 class="text-center">Book an appointment</h3>
   <%= simple_form_for [@artist, @booking] do |f| %>
   <%= f.input :start_time %>
   <%= f.input :end_time %>
   <%= f.submit "book" %>
   <% end %>
 </div>
</div>

app/views/comments/new.html.erb
<div class="col-lg-4 col-lg-offset-4">
    <%= simple_form_for [@tattoo.artist, @tattoo, @comment] do |f| %>
    <%= f.input :comment %>
    <%= f.button :submit %>
    <% end %>
  </div>

app/views/conversations/index.html.erb
<% @conversations.each do |conversation| %>
  <% if current_user && conversation.user.id == current_user.id %>
    <%= link_to conversation.artist.name, conversation_messages_path(conversation) %>
  <% end %>
  <% if current_artist && conversation.artist.id == current_artist.id %>
      <%= link_to conversation.user.name, conversation_messages_path(conversation) %>
  <% end %>
<% end %>

app/views/conversations/new.html.erb
new.html.erb

app/views/layouts/_dashboard_artist.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-4 col-lg-4">
      <h3>Welcome, <%= current_artist.name %>!</h3>


      <%= link_to "Upload photos of your work", new_artist_tattoo_path(current_artist) %>
</div>

<div>
  <%= week_calendar number_of_weeks: 1, events: current_artist.bookings do |date, bookings| %>
  <%= date %>
    <% bookings.each do |booking| %>
    <div class="cal-event">
      <%= booking.start_time.strftime("%H:%M") %>-<%=booking.end_time.strftime("%H-%M")  %> (<%= booking.user.name %>)
    </div>
    <% end %>
  <% end  %>
  <div class="text-center">
    <button class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg">Monthly  Calendar</button>
  </div>
</div>


<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <%= month_calendar events: current_artist.bookings do |date, bookings| %>
       <%= date %>
      <% bookings.each do |booking| %>
      <div class="cal-event">
      <%= booking.start_time.strftime("%H:%M")%>-<%= booking.end_time.strftime("%H:%M")%> (<%= booking.user.name %>)
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_dashboard_user.html.erb
<div class="text-center">
<h1>Welcome, <%= current_user.name %></h1>
<% if current_user && current_user.bookings.count > 0 %>
  <h3>Your upcoming appointments:</h3>
  <% current_user.bookings.each do |booking| %>
    <div class="appointment-card" style= "background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.tattoodo.com/images/0/20728.jpg');">
      <div class="appointment-date">
      <h3>
      <%= booking.start_time.strftime("%A") %>,
      <%= booking.start_time.strftime("%B") %> <%= booking.start_time.strftime("%d") %>
      </h3>
      </div>
      <div class="appointment-time">
        <%= booking.start_time.strftime("%H") %>:<%= booking.start_time.strftime("%M") %> -
        <%= booking.end_time.strftime("%H") %>:<%= booking.end_time.strftime("%M") %>
      </div>
      <div class="appointment-artist"><%= link_to booking.artist.name, artist_path(booking.artist) %></div>
      <div class="appointment-avatar"><%= image_tag booking.artist.avatar, class: "artist-avatar-small" %></div>
    </div>
  <% end %>
<% elsif current_user && current_user.bookings.count == 0 %>
<h3>You don't have any upcoming appointments</h3>
<%= link_to "Browse work", root_path %>
<% end %>
</div>

app/views/layouts/_modal.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    **here comes whatever you want to show!**
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Inkd</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400" rel="stylesheet">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4">
    <%= simple_form_for [@conversation, @message] do |f| %>
    <%= f.input :body %>
    <%= f.button :submit, "Send" %>
    <% end %>
  </div>
</div>

app/views/messages/_form1.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4">
    <%= simple_form_for [@conversation, @message] do |f| %>
    <%= f.input :subject %>
    <%= f.input :body %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.button :submit, "Send" %>
    <% end %>
  </div>
</div>

app/views/messages/_form2.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4">
    <%= simple_form_for [@conversation, @message] do |f| %>
    <%= f.input :body %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.button :submit, "Send" %>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="text-center">
  <% @messages.each do |message| %>
  <div>
  <ul style="list-style: none">
    <% if message.artist %>
      <li><%= message.artist.name %></li>
    <% end %>
    <% if message.user %>
      <li><%= message.user.name %></li>
    <% end %>
      <% if message.created_at %>
      <li><%= message.created_at.strftime("%M/%d/%Y") %> at <%= message.created_at.strftime("%H:%M") %></li>
      <% end %>
      <li><%= message.body %></li>
  </ul>
    <% if message.photo %>
      <%= cl_image_tag message.photo.path, width: 200, height: 200, crop: :thumb %>
    <% end %>

  <% end %>
  </div>
</div>

<% if @messages.count >= 1 %>
  <%= render partial: "messages/form2", locals: { messages: @messages} %>
<% else %>
  <%= render partial: "messages/form1", locals: { messages: @messages} %>
<% end %>

app/views/messages/new.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4">
    <%= simple_form_for [@conversation, @message] do |f| %>
    <%= f.input :body %>
    <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/pages/_banner.html.erb
<div class="banner text-center">
  <h1>Inkd.</h1>
  <h3>Connect with top local tattoo artists</h3>

  <%= form_tag "/artists", method: "get" do |f| %>
  <%= select_tag "city", options_for_select(cities) %>
  <%= submit_tag "Discover Art", class: 'btn-primary ' %>

  <% end %>
  <div class="call-to-action-user">
    <%= link_to "User sign in", new_user_session_path %> | <%= link_to "User sign up", new_user_registration_path %>
  </div>
  <div class="call-to-action-artist">
    <%= link_to "Artist sign in", new_artist_session_path %> | <%= link_to "Artist sign up", new_artist_registration_path %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<% if current_user %>
  <%= render 'layouts/dashboard_user' %>
<% else %>
  <%= render 'layouts/dashboard_artist' %>
<% end %>

app/views/pages/home.html.erb
<%= render partial: "banner", locals: { cities: @cities} %>

app/views/reviews/new.html.erb
<%= simple_form_for [@artist, @review] do |f| %>
<%= f.input :content %>
<%= f.button :submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? || artist_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Dashboard", pages_dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Search", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", conversations_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if current_artist %>
              <li>
                <%= link_to artist_path(current_artist)  do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
            <% end %>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "User login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %> |  <%= link_to t(".sign_in", default: "Artist login"), new_artist_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/tattoos/new.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4">
    <%= simple_form_for [current_artist, @tattoo] do |f| %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.button :submit, "Upload" %>
    <% end %>
  </div>
</div>

app/views/tattoos/show.html.erb
<div class="container-postion-relative">
  <div>
    <%= link_to artist_path(@tattoo.artist) do %>
      <%= image_tag @tattoo.url, class: "tattoo-show-photo" %>
    <% end %>
  </div>
  <div class="tat-show-artist-info">
    <div>
      <%= link_to artist_path(@tattoo.artist) do  %>
      <%= image_tag @tattoo.artist.avatar, class: "artist-avatar-small"%>
      <% end %>
    </div>
    <div class="artist-name">
      <%= link_to @tattoo.artist.name, artist_path(@tattoo.artist) %>
    </div>
      </div>


      <div id="comment-box">
        <i class="fa fa-comment-o fa-2x" aria-hidden="true"></i>
        <%= simple_form_for [@tattoo.artist, @tattoo, @comment] do |f| %>
        <%= f.input :rollout_id, :label => false, wrapper_html: {class: "form-inline"} do %>
        <%= f.input :comment, inline_label: "", label: false %>
        <%= f.button :submit, "submit", class: "btn-primary" %>
        <% end %>
        <% end %>
      </div>
        <% if @tattoo.comments %>
        <div id="comments">
        <% @tattoo.comments.each do |comment| %>
          <ul style="list-style:none" class="list-inline">
            <% if comment.user %>
              <li class="comment-user"><b><%= comment.user.name %></b></li>
            <% end %>
            <li><%=comment.comment %></li>
          </ul>
        <% end %>
        </div>
      <% end %>


  </div>
</div>